# Default configuration
# (fallback value if the key isn't present in the config file or on the command line)
port: 8080
device: "/dev/video0"
resolution: "auto"
no_audio: false
no_echo_cancel: false
# flip: "horizontal"