pre-release-commit-message = "release: {{version}}"
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}"},
  {file="CHANGELOG.md", search="TBD", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - TBD\n\n"},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/gourlaysama/dcamctl/compare/{{tag_name}}...HEAD"},
  {file="README.md", search="-b v.+\n\\$", replace="-b v{{version}}\n$"},
  {file="README.md", search="--version\ndcamctl .+", replace="--version\ndcamctl {{version}}"},
  {file="README.md", search="/blob/v.+/config.yml", replace="/blob/v{{version}}/config.yml"},
]
post-release-commit-message = "release: bumping to {{next_version}}"
tag-message = "release: {{crate_name}} version {{version}}"
sign-commit = true
sign-tag = true
disable-publish = true
dev-version-ext = "dev"